services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lula
    ports:
      - "8888:8888"
    volumes:
      - ./${UNIT_PATH}:/app
    environment:
      UNIT_PATH: ${UNIT_PATH}
    command: ["/init.sh"]
    tty: true
