services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data 
      - "./pi_mod_03/scripts/db/:/docker-entrypoint-initdb.d/"
    tty: true

  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project
    env_file: .env
    command: ["/init.sh"]
    ports:
      - "8888:8888"
    volumes:
      - ./pi_mod_03:/app
      - ./pi_mod_03/scripts/init.sh:/init.sh 
      - ./pi_mod_03/dbt_project/profiles:/app/.dbt  
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  database_data:
