services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - database_data:/var/lib/postgresql/data 
      - "./${DB_PATH}/01_init_db.sql:/docker-entrypoint-initdb.d/01_init_db.sql"
    tty: true

  project:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project
    env_file: .env
    command: ["/init.sh"]
    ports:
      - "8888:8888"
    volumes:
      - ./${UNIT_PATH}:/app
      - ./MOD2/LECTURE1/scripts/init.sh:/init.sh 
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  database_data:
