version: 2

sources:
  - name: public
    tables:
      - name: categories
        identifier: Categorias
models:
  - name: stg_categories
    description: "Staging model for categories, with cleaning and validation"
    columns:
      - name: name
        description: "Name of the category"
        tests:
          - not_null
          - unique
      - name: user_id
        tests:
          - not_null
          - unique