version: 2

sources:
  - name: public
    tables:
      - name: shipping_addresses
        identifier: DireccionesEnvio

models:
  - name: stg_shipping_addresses
    description: "Staging model for shipping addresses, with cleaning and validation"
    columns:
      - name: address_id
        description: "Unique identifier for the shipping address"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Identifier for the user associated with the shipping address"
        tests:
          - not_null
          - unique
      - name: street
        description: "Street address for shipping"
        tests:
          - not_null
      - name: city
        description: "City for shipping"
        tests:
          - not_null
      - name: state
        description: "State or region for shipping"
      - name: province
        description: "Province for shipping"
        tests:
          - not_null
      - name: district
        description: "District for shipping"
      - name: zip_code
        description: "Postal code for shipping"
        tests:
          - not_null
      - name: country
        description: "Country for shipping"
        tests:
          - not_null
      - name: department
        description: "Department for shipping"