
services:
  script-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lula
    command: ["/init.sh"]
    ports:
      - "8888:8888"     
    volumes:
      - ./app:/app   
    tty: true
