version: '3.8'

services:
  script-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lula
    command: ["/init.sh"]
    tty: true                             # Permite modo interactivo (importante para sh/bash)
