version: 2

sources:
  - name: public
    tables:
      - name: orders
        identifier: Ordenes

models:
  - name: stg_orders
    description: "Staging model for orders, with cleaning and validation"
    columns:
      - name: order_id
        description: "Unique identifier for the order"
        tests:
          - not_null
          - unique
      - name: user_id
        description: "Identifier for the user who placed the order"
        tests:
          - not_null
      - name: order_date
        description: "Date when the order was placed"
        tests:
          - not_null
      - name: total
        description: "Total amount for the order"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "total >= 0"
      - name: order_status
        description: "Status of the order (e.g., pending, completed, cancelled)"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'completed', 'cancelled', 'shipped']
