version: 2

sources:
  - name: public
    tables:
      - name: carts
        identifier: Categorias
models:
  - name: stg_carts
    description: "Staging model for carts, with cleaning and validation"
    columns:
      - name: quantity
        description: "Quantity of items in the cart"
        tests:
          - not_null
      - name : added_date
        description: "Date when the item was added to the cart"
        tests:
          - not_null