version: 2

sources:
  - name: public
    tables:
      - name: users         # alias
        identifier: Usuarios # nombre físico

models:
  - name: stg_users
    description: "Staging model for users, with email cleaning and validation"
    columns:
      - name: email
        description: "Email address of the user, cleaned and validated, must be unique and not null"
        tests:
          - not_null
          - unique
          - dbt_utils.expression_is_true:
              expression: "lower(email) ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'"
      - name: user_id
        tests:
          - not_null
          - unique
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
